gb:arrcopy.c arrcopyfrompos.c sumofrow.c sumofcol.c sumofdiagonal.c sumofuprtriangle.c sumoflwrtriangle.c
	gcc arrcopy.c arrcopyfrompos.c sumofrow.c sumofcol.c sumofdiagonal.c sumofuprtriangle.c sumoflwrtriangle.c -o gb

